### ISSUE TITLE
Next WG Note Path

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#232]
For the publication of the new working group note, I will collect the to-dos in the issue thread. This comment will be updated based on the comments below.

Our Primary To Dos:
- [x]  Move temporary sections back into the main body or delete them when needed: https://github.com/w3c/wot-binding-templates/issues/220 (includes https://github.com/w3c/wot-binding-templates/pull/228) . This should also help with https://github.com/w3c/wot-binding-templates/issues/213
- [x]  Clarifying terms and bindings relationships: https://github.com/w3c/wot-binding-templates/issues/218
- [x]  Deciding on the prefixes: https://github.com/w3c/wot-binding-templates/issues/120
- [x] Clarifying the binding mechanism: https://github.com/w3c/wot-binding-templates/issues/238

Strech Goals that are optional:
- [x]  Explaining how to validate TDs that have protocol bindings: https://github.com/w3c/wot-binding-templates/issues/231
- [x]  CoAP Ontology
- [x]  JSON Schemas for Protocol Bindings (#227, #229, #230)
- [ ]  XML Binding (https://github.com/w3c/wot-binding-templates/issues/139)
- [ ]  Possible Mappings (https://github.com/w3c/wot-binding-templates/issues/203)

Note: If this gets too complicated, I will create GitHub project.

**Comment by egekorkan** [comment]
Call of 05.04: Closing
